### ISSUE TITLE
I can install it, but I can't seem to run any commands. I tried running the following command in an ipynb file:

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter-powertoys#34]
I can install it, but I can't seem to run any commands. I tried running the following command in an ipynb file:
![Screenshot showing the edit kernelspec command failing with a dialog](https://user-images.githubusercontent.com/7199958/171507707-443d10ea-4123-47c7-a47f-d48884982986.PNG)

_Originally posted by @rzhao271 in https://github.com/microsoft/vscode-jupyter/issues/9251#issuecomment-1144174734_

**Comment by DonJayamanne** [comment]
Unable to repro, should be fixedc

**Comment by rzhao271** [comment]
I still get the error, even when using a fresh user data dir and extension dir.

![Error message, saying the kernelspec cannot be updated](https://user-images.githubusercontent.com/7199958/206052876-101f7c06-ab87-4546-bccd-756c7cb66dfd.png)
